import { createHmac, randomBytes } from "node:crypto";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const requestContext = vi.hoisted(() => ({
  headerValues: {} as Record<string, string>,
  sessionValue: "session-a",
}));

vi.mock("next/headers", () => ({
  cookies: vi.fn(async () => ({
    get: () => ({ value: requestContext.sessionValue }),
  })),
  headers: vi.fn(async () => new Headers(requestContext.headerValues)),
}));

import {
  assertServerActionOrigin,
  assertServerActionSecurity,
  CSRF_FIELD_NAME,
  getCsrfToken,
  verifyCsrfToken,
} from "@/lib/csrf";

function setRequestContext(headerValues: Record<string, string> = {}, sessionValue = "session-a") {
  requestContext.headerValues = headerValues;
  requestContext.sessionValue = sessionValue;
}

function signedCsrfValue(issuedAt: number, nonce = "nonce-a", fingerprint = "fingerprint-a") {
  const body = `${issuedAt}.${nonce}.${fingerprint}`;
  const signature = createHmac("sha256", process.env.CSRF_SECRET ?? "").update(body).digest("base64url");
  return `${body}.${signature}`;
}

beforeEach(() => {
  vi.stubEnv("CSRF_SECRET", randomBytes(32).toString("base64url"));
  vi.stubEnv("NEXT_PUBLIC_APP_URL", "https://configured.example.test");
  setRequestContext({ host: "request.example.test" });
});

afterEach(() => {
  vi.unstubAllEnvs();
  vi.useRealTimers();
});

describe("assertServerActionOrigin", () => {
  it("rejects a cross-origin Origin", async () => {
    setRequestContext({ host: "request.example.test", origin: "https://attacker.example.test" });

    await expect(assertServerActionOrigin()).rejects.toThrow("Invalid request origin.");
  });

  it("rejects a cross-origin Referer", async () => {
    setRequestContext({ host: "request.example.test", referer: "https://attacker.example.test/form" });

    await expect(assertServerActionOrigin()).rejects.toThrow("Invalid request origin.");
  });

  it("accepts an Origin matching the configured app URL", async () => {
    setRequestContext({ host: "request.example.test", origin: "https://configured.example.test" });

    await expect(assertServerActionOrigin()).resolves.toBeUndefined();
  });

  it("accepts a Referer matching Host", async () => {
    vi.stubEnv("NEXT_PUBLIC_APP_URL", "");
    setRequestContext({ host: "request.example.test", referer: "https://request.example.test/form" });

    await expect(assertServerActionOrigin()).resolves.toBeUndefined();
  });

  it("accepts an Origin matching X-Forwarded-Host", async () => {
    vi.stubEnv("NEXT_PUBLIC_APP_URL", "");
    setRequestContext({
      "x-forwarded-host": "public.example.test",
      "x-forwarded-proto": "https",
      origin: "https://public.example.test",
    });

    await expect(assertServerActionOrigin()).resolves.toBeUndefined();
  });
});

describe("CSRF tokens", () => {
  it("verifies a signed value generated by getCsrfToken", async () => {
    const csrfValue = await getCsrfToken();

    await expect(verifyCsrfToken(csrfValue)).resolves.toBe(true);
  });

  it("rejects missing and malformed values", async () => {
    await expect(verifyCsrfToken(null)).resolves.toBe(false);
    await expect(verifyCsrfToken("only.three.parts")).resolves.toBe(false);
  });

  it("binds values to the current session fingerprint", async () => {
    const csrfValue = await getCsrfToken();
    setRequestContext({ host: "request.example.test" }, "session-b");

    await expect(verifyCsrfToken(csrfValue)).resolves.toBe(false);
  });

  it("rejects expired values and timestamps more than one minute in the future", async () => {
    vi.useFakeTimers();
    const now = new Date("2026-07-14T12:00:00.000Z");
    vi.setSystemTime(now);
    const currentValue = await getCsrfToken();
    const [, nonce, fingerprint] = currentValue.split(".");

    const ttlBoundaryValue = signedCsrfValue(now.getTime() - (2 * 60 * 60 * 1000), nonce, fingerprint);
    const futureBoundaryValue = signedCsrfValue(now.getTime() + 60_000, nonce, fingerprint);
    const expiredValue = signedCsrfValue(now.getTime() - (2 * 60 * 60 * 1000) - 1, nonce, fingerprint);
    const futureValue = signedCsrfValue(now.getTime() + 60_001, nonce, fingerprint);

    await expect(verifyCsrfToken(ttlBoundaryValue)).resolves.toBe(true);
    await expect(verifyCsrfToken(futureBoundaryValue)).resolves.toBe(true);
    await expect(verifyCsrfToken(expiredValue)).resolves.toBe(false);
    await expect(verifyCsrfToken(futureValue)).resolves.toBe(false);
  });

  it("rejects tampering with every signed part", async () => {
    const csrfValue = await getCsrfToken();
    const [issuedAt, nonce, fingerprint, signature] = csrfValue.split(".");
    const changedValues = [
      `${Number(issuedAt) + 1}.${nonce}.${fingerprint}.${signature}`,
      `${issuedAt}.other-nonce.${fingerprint}.${signature}`,
      `${issuedAt}.${nonce}.other-fingerprint.${signature}`,
      `${issuedAt}.${nonce}.${fingerprint}.${signature.slice(0, -1)}${signature.endsWith("x") ? "y" : "x"}`,
    ];

    for (const changedValue of changedValues) {
      await expect(verifyCsrfToken(changedValue)).resolves.toBe(false);
    }
  });
});

describe("assertServerActionSecurity", () => {
  it("accepts FormData carrying a valid value for the CSRF field", async () => {
    setRequestContext({ host: "request.example.test", origin: "https://configured.example.test" });
    const csrfValue = await getCsrfToken();
    const formData = new FormData();
    formData.set(CSRF_FIELD_NAME, csrfValue);

    await expect(assertServerActionSecurity(formData)).resolves.toBeUndefined();
  });

  it("rejects FormData missing the CSRF field", async () => {
    setRequestContext({ host: "request.example.test", origin: "https://configured.example.test" });

    await expect(assertServerActionSecurity(new FormData())).rejects.toThrow("Invalid CSRF token.");
  });

  it("rejects FormData with an invalid CSRF field value", async () => {
    setRequestContext({ host: "request.example.test", origin: "https://configured.example.test" });
    const formData = new FormData();
    formData.set(CSRF_FIELD_NAME, "invalid");

    await expect(assertServerActionSecurity(formData)).rejects.toThrow("Invalid CSRF token.");
  });
});
