import { beforeEach, afterEach, describe, expect, it, vi } from "vitest";
import { Prisma } from "@prisma/client";
import { decryptSensitiveValue } from "./sensitive-data";
import { recordLearnerNotificationSourceEvent, materializeLearnerNotificationSourceEvent } from "./learner-notification-source-events";
import { enqueueLearnerNotificationInTransaction } from "./learner-notification-outbox";
vi.mock("./learner-notification-outbox", async original => ({ ...await original<typeof import("./learner-notification-outbox")>(), enqueueLearnerNotificationInTransaction: vi.fn() }));
const input={vendorId:"vendor",productId:"course",event:"lesson_published" as const,eventIdentity:"published_1",audienceCustomerKeyHash:null,occurredAt:new Date("2026-10-01T00:00:00Z"),message:{title:"Lesson",body:"Synthetic private title",path:"/portal/vendor/learn/course"}};
async function fixture(){
 let source:Record<string,unknown>={};
 const tx={learnerNotificationSourceEvent:{upsert:vi.fn(async ({create}:{create:Record<string,unknown>})=>{source={id:"source",...create,revision:1,completedAt:null,preferenceCursor:null};return {id:"source"};}),findFirst:vi.fn(async()=>source),updateMany:vi.fn(async()=>({count:1})),update:vi.fn(async()=>({}))},learnerNotificationPreference:{findMany:vi.fn(async()=>[] as Array<{id:string;customerKeyHash:string;channel:string}>)}};
 await recordLearnerNotificationSourceEvent(tx as never,input);
 const db={$transaction:vi.fn(async (run:(store:typeof tx)=>unknown)=>run(tx))};return {tx,db,source};
}
beforeEach(()=>{vi.stubEnv("CSRF_SECRET","synthetic-source-events-encryption-key-32-bytes");vi.mocked(enqueueLearnerNotificationInTransaction).mockReset();vi.mocked(enqueueLearnerNotificationInTransaction).mockResolvedValue({id:"delivery",status:"queued"});});
afterEach(()=>vi.unstubAllEnvs());
describe("domain source security and bounded consumption",()=>{
 it("rejects publication IDs that cannot enter delivery deduplication",async()=>{const f=await fixture();await expect(recordLearnerNotificationSourceEvent(f.tx as never,{...input,eventIdentity:"lesson:date"})).rejects.toThrow();expect(f.tx.learnerNotificationSourceEvent.upsert).toHaveBeenCalledTimes(1);});
 it("encrypts private content with the exact tenant/course/event binding",async()=>{const f=await fixture();const purpose=`learner-notification-source-v1:${JSON.stringify([input.vendorId,input.productId,input.event,input.eventIdentity])}`;expect(String(f.source.payloadEncryptedEnvelope)).not.toContain(input.message.body);expect(JSON.parse(decryptSensitiveValue(String(f.source.payloadEncryptedEnvelope),purpose))).toEqual(input.message);expect(()=>decryptSensitiveValue(String(f.source.payloadEncryptedEnvelope),purpose+"foreign")).toThrow();});
 it.each([["../vendor","source"],["vendor","../source"]])("rejects malformed source scope %s %s before a transaction",async(vendor,id)=>{const f=await fixture();await expect(materializeLearnerNotificationSourceEvent(f.db as never,vendor,id)).rejects.toThrow();expect(f.db.$transaction).not.toHaveBeenCalled();});
 it("cannot expand a missing or foreign source",async()=>{const f=await fixture();f.tx.learnerNotificationSourceEvent.findFirst.mockResolvedValueOnce(null as never);expect(await materializeLearnerNotificationSourceEvent(f.db as never,"foreign","source")).toEqual({status:"not_pending",queued:0});expect(f.tx.learnerNotificationPreference.findMany).not.toHaveBeenCalled();expect(f.tx.learnerNotificationSourceEvent.findFirst).toHaveBeenCalledWith({where:{vendorId:"foreign",id:"source",completedAt:null}});});
 it("does not expand a lost revision claim",async()=>{const f=await fixture();f.tx.learnerNotificationSourceEvent.updateMany.mockResolvedValueOnce({count:0});expect((await materializeLearnerNotificationSourceEvent(f.db as never,"vendor","source")).status).toBe("claimed_elsewhere");expect(enqueueLearnerNotificationInTransaction).not.toHaveBeenCalled();});
 it("persists at most twenty recipients and leaves a resumable page",async()=>{const f=await fixture();f.tx.learnerNotificationPreference.findMany.mockResolvedValueOnce(Array.from({length:21},(_,i)=>({id:`pref${i}`,customerKeyHash:"a".repeat(43),channel:"email"})));expect(await materializeLearnerNotificationSourceEvent(f.db as never,"vendor","source")).toEqual({status:"page_materialized",queued:20});expect(enqueueLearnerNotificationInTransaction).toHaveBeenCalledTimes(20);expect(f.tx.learnerNotificationSourceEvent.update).toHaveBeenCalledWith({where:{id:"source"},data:{preferenceCursor:"pref19",completedAt:null}});});
 it("filters exact audience, prior consent and persisted cursor; revoked recipients still advance",async()=>{const f=await fixture();f.source.audienceCustomerKeyHash="a".repeat(43);f.source.preferenceCursor="prior";f.tx.learnerNotificationPreference.findMany.mockResolvedValueOnce([{id:"next",customerKeyHash:"a".repeat(43),channel:"email"}]);vi.mocked(enqueueLearnerNotificationInTransaction).mockResolvedValueOnce(null);expect((await materializeLearnerNotificationSourceEvent(f.db as never,"vendor","source")).queued).toBe(0);expect(f.tx.learnerNotificationPreference.findMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({customerKeyHash:"a".repeat(43),id:{gt:"prior"},consentedAt:{lte:input.occurredAt}}),take:21}));expect(f.tx.learnerNotificationSourceEvent.update).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({preferenceCursor:"next",completedAt:expect.any(Date)})}));});
 it("completes an empty audience without changing an existing cursor",async()=>{const f=await fixture();f.source.preferenceCursor="prior";expect((await materializeLearnerNotificationSourceEvent(f.db as never,"vendor","source")).status).toBe("completed");expect(f.tx.learnerNotificationSourceEvent.update).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({preferenceCursor:"prior"})}));});
 it.each(["P2002","P2034"])("retries only a bounded DB conflict %s",async code=>{const f=await fixture();f.db.$transaction.mockRejectedValueOnce(new Prisma.PrismaClientKnownRequestError("synthetic conflict",{code,clientVersion:"synthetic"}));expect((await materializeLearnerNotificationSourceEvent(f.db as never,"vendor","source")).status).toBe("completed");expect(f.db.$transaction).toHaveBeenCalledTimes(2);});
 it("exhausts DB conflict retries without unbounded looping",async()=>{const f=await fixture();f.db.$transaction.mockRejectedValue(new Prisma.PrismaClientKnownRequestError("synthetic conflict",{code:"P2034",clientVersion:"synthetic"}));await expect(materializeLearnerNotificationSourceEvent(f.db as never,"vendor","source")).rejects.toThrow();expect(f.db.$transaction).toHaveBeenCalledTimes(3);});
 it.each([new Error("synthetic non-DB failure"),new Prisma.PrismaClientKnownRequestError("synthetic other DB failure",{code:"P2010",clientVersion:"synthetic"})])("does not retry corruption or unrelated DB failures",async error=>{const f=await fixture();f.db.$transaction.mockRejectedValueOnce(error);await expect(materializeLearnerNotificationSourceEvent(f.db as never,"vendor","source")).rejects.toThrow();expect(f.db.$transaction).toHaveBeenCalledTimes(1);});
 it("rejects swapped ciphertext without expanding recipients or persisting cursor",async()=>{const f=await fixture();f.source.vendorId="foreign";await expect(materializeLearnerNotificationSourceEvent(f.db as never,"vendor","source")).rejects.toThrow();expect(f.tx.learnerNotificationPreference.findMany).not.toHaveBeenCalled();expect(f.tx.learnerNotificationSourceEvent.update).not.toHaveBeenCalled();});
});
