import { beforeEach, describe, expect, it, vi } from "vitest";
import { continueWp4BuyerRefund, continueWp4BuyerReconcile, WP4_CURRENT_BUYER_CONTINUATION_SOURCE_SHA } from "./wp4-payuni-buyer-continuation";
import { WP4_SANDBOX_FIXTURE } from "./wp4-sandbox-fixture";
const mocks = vi.hoisted(() => ({ tx: vi.fn(), events: vi.fn(), refunds: vi.fn(), refund: vi.fn(), reconcile: vi.fn() }));
vi.mock("@/lib/wp4-payuni-sandbox-refund-execution", () => ({ executeNextWp4PayUniSandboxRefund: mocks.refund }));
vi.mock("@/lib/wp4-payuni-sandbox-reconciliation", async () => { const actual = await vi.importActual<typeof import("@/lib/wp4-payuni-sandbox-reconciliation")>("@/lib/wp4-payuni-sandbox-reconciliation"); return { ...actual, reconcileWp4PayUniSandboxRefund: mocks.reconcile }; });
const db = { paymentTransaction: { findMany: mocks.tx }, webhookEvent: { findMany: mocks.events }, refundRecord: { findMany: mocks.refunds } } as never;
const row = (status = "paid", overrides: Record<string, unknown> = {}) => ({ id: "tx", vendorId: WP4_SANDBOX_FIXTURE.vendorId, providerName: "payuni", orderNumber: "WP4-ORDER", providerTradeNo: "trade", grossAmountCents: 100, refundedAmountCents: 0, status, metadata: { wp4SourceCommit: WP4_CURRENT_BUYER_CONTINUATION_SOURCE_SHA, billingPurpose: "buyer_order", productId: WP4_SANDBOX_FIXTURE.productId, wp4PaymentSubmissionReserved: true }, ...overrides });
beforeEach(() => { vi.clearAllMocks(); mocks.tx.mockResolvedValue([row()]); mocks.events.mockResolvedValue([{ id: "e" }]); mocks.refunds.mockResolvedValue([]); mocks.refund.mockResolvedValue({ status: "COMPLETED", providerWriteAttempted: true }); mocks.reconcile.mockResolvedValue({ status: "RECONCILED", reconciled: true }); });
describe("fixed buyer continuation", () => {
  it("delegates refund only after processed callback and no refund", async () => { await expect(continueWp4BuyerRefund(db)).resolves.toMatchObject({ status: "COMPLETED" }); expect(mocks.refund).toHaveBeenCalledExactlyOnceWith(db, WP4_CURRENT_BUYER_CONTINUATION_SOURCE_SHA, undefined, "tx"); });
  it("rejects pending and existing refund without delegate", async () => { mocks.refund.mockClear(); mocks.tx.mockResolvedValue([row("pending")]); await expect(continueWp4BuyerRefund(db)).resolves.toMatchObject({ status: "REFUND_NOT_ELIGIBLE" }); expect(mocks.refund).not.toHaveBeenCalled(); mocks.tx.mockResolvedValue([row()]); mocks.events.mockResolvedValue([{ id: "e" }]); mocks.refunds.mockResolvedValue([{ id: "r" }]); await expect(continueWp4BuyerRefund(db)).resolves.toMatchObject({ status: "REFUND_NOT_ELIGIBLE" }); expect(mocks.refund).not.toHaveBeenCalled(); });
  it("rejects invalid fixed identity, reference, and amount before delegation", async () => { for (const metadata of [{ ...row().metadata, billingPurpose: "platform_subscription" }, { ...row().metadata, productId: "other" }, { ...row().metadata, wp4PaymentSubmissionReserved: false }, { ...row().metadata, wp4SourceCommit: "b".repeat(40) }]) { mocks.tx.mockResolvedValue([row("paid", { metadata })]); await expect(continueWp4BuyerRefund(db)).resolves.toMatchObject({ status: "FIXTURE_UNAVAILABLE" }); } mocks.tx.mockResolvedValue([row("paid", { providerTradeNo: null })]); await expect(continueWp4BuyerRefund(db)).resolves.toMatchObject({ status: "REFUND_NOT_ELIGIBLE" }); mocks.tx.mockResolvedValue([row("paid", { grossAmountCents: 200 })]); await expect(continueWp4BuyerRefund(db)).resolves.toMatchObject({ status: "REFUND_NOT_ELIGIBLE" }); });
  it("requires one processed event and fixed source", async () => { mocks.tx.mockResolvedValue([row("paid", { metadata: { wp4SourceCommit: "b".repeat(40) } })]); await expect(continueWp4BuyerReconcile(db)).resolves.toMatchObject({ status: "FIXTURE_UNAVAILABLE" }); mocks.tx.mockResolvedValue([row(), row()]); await expect(continueWp4BuyerReconcile(db)).resolves.toMatchObject({ status: "CANDIDATE_AMBIGUOUS" }); mocks.tx.mockResolvedValue([row()]); mocks.events.mockResolvedValue([]); await expect(continueWp4BuyerReconcile(db)).resolves.toMatchObject({ status: "PENDING_RESERVATION_UNAVAILABLE" }); mocks.events.mockResolvedValue([{ id: "a" }, { id: "b" }]); await expect(continueWp4BuyerReconcile(db)).resolves.toMatchObject({ status: "CANDIDATE_AMBIGUOUS" }); });
  it("delegates reconciliation with the server-selected transaction id", async () => { await expect(continueWp4BuyerReconcile(db)).resolves.toMatchObject({ status: "RECONCILED", reconciled: true }); expect(mocks.reconcile).toHaveBeenCalledExactlyOnceWith(db, WP4_CURRENT_BUYER_CONTINUATION_SOURCE_SHA, "tx"); });
});
