// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: ".env.local" });
config({ path: ".env" });

function migrationDatabaseUrl() {
  const directUrl = process.env["DIRECT_URL"];
  if (directUrl) return directUrl;

  const runtimeUrl = process.env["DATABASE_URL"];
  if (runtimeUrl && !runtimeUrl.startsWith("file:")) return runtimeUrl;

  return "postgresql://postgres:postgres@localhost:54329/celebratedeal_dev?schema=public";
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node --import tsx prisma/seed.ts",
  },
  datasource: {
    url: migrationDatabaseUrl(),
  },
});
