import {randomUUID} from "node:crypto";
import {expect,test} from "@playwright/test";
import {PrismaClient} from "@prisma/client";
import {saveCourseLesson} from "../../src/lib/course-curriculum";
import {automationCustomerKeyHash} from "../../src/lib/automation-workflow";
import {protectCommerceOrderPii} from "../../src/lib/commerce-order-pii";
import {grantCommerceEntitlement} from "../../src/lib/commerce-order-fulfillment";
import {revealEmailDeliveryPayload} from "../../src/lib/email-delivery-pii";
import {reconcileCommerceOrderRefund} from "../../src/lib/commerce-orders";
test.use({trace:"off",screenshot:"off",video:"off",serviceWorkers:"allow"});test.setTimeout(180000);
test("English mailbox login, course and discussion persist locale; PWA stores only public assets and denies offline writes",async({page,baseURL})=>{
 const db=new PrismaClient(),suffix=randomUUID(),email=`locale-${suffix}@example.test`;
 const vendor=await db.vendor.create({data:{name:"合成雙語學院",slug:`locale-${suffix}`,email:`${suffix}@example.test`,passwordHash:"synthetic-only"}});
 const foreign=await db.vendor.create({data:{name:"合成其他學院",slug:`foreign-locale-${suffix}`,email:`foreign-${suffix}@example.test`,passwordHash:"synthetic-only"}});
 const product=await db.product.create({data:{vendorId:vendor.id,name:"保留原文的課程",slug:randomUUID(),priceCents:10000,commerceDomain:"course",fulfillmentType:"course"}});
 await saveCourseLesson(db,vendor.id,{productId:product.id,revision:product.revision,chapterTitle:"原文章節",title:"原文單元",durationSeconds:100,videoUrl:"https://media.example.test/synthetic.mp4",published:true});
 const orderId=randomUUID(),pii=protectCommerceOrderPii({buyer:{name:"合成學員",email},shipping:null},{vendorId:vendor.id,orderId});
 await db.commerceOrder.create({data:{id:orderId,vendorId:vendor.id,orderNumber:orderId,checkoutIdempotencyKey:randomUUID(),checkoutIdentityHash:pii.checkoutIdentityHash,automationCustomerKeyHash:automationCustomerKeyHash(vendor.id,email),status:"paid",subtotalAmountCents:10000,totalAmountCents:10000,paidAmountCents:10000,buyerEncryptedEnvelope:pii.buyerEncrypted,buyerMaskedName:pii.buyerNameMasked,buyerMaskedEmail:pii.buyerEmailMasked}});
 const item=await db.commerceOrderItem.create({data:{vendorId:vendor.id,orderId,productId:product.id,lineIndex:0,productName:product.name,productSlug:product.slug,commerceDomain:"course",fulfillmentType:"course",unitPriceCents:10000,quantity:1,lineTotalCents:10000,nonSensitiveSnapshot:{}}});
 const entitlement=await db.commerceEntitlement.create({data:{vendorId:vendor.id,orderItemId:item.id}});
 await db.$transaction(tx=>grantCommerceEntitlement(tx,{vendorId:vendor.id,entitlementId:entitlement.id,expectedRevision:entitlement.revision,actor:{id:"synthetic-localization-fixture"}}));
 const portal=`/portal/${vendor.slug}`,course=`${portal}/learn/${product.id}`;
 try{
  await page.context().route(url=>url.origin!==new URL(baseURL!).origin,route=>route.abort());
  await page.goto(`${portal}/login`);
  await page.getByRole("combobox",{name:"語言",exact:true}).selectOption("en");
  await page.getByRole("button",{name:"套用",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Return to your learning centre",exact:true})).toBeVisible();
  await expect(page.locator('div[lang="en"]')).toBeVisible();
  await page.getByLabel("Email",{exact:true}).fill(email);
  await page.getByRole("button",{name:"Send sign-in link",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("15 minutes");
  // Read only this owned synthetic delivery; never call an external mail provider.
  await expect.poll(()=>db.emailDelivery.count({where:{vendorId:vendor.id,trigger:"student_portal_magic_link"}})).toBe(1);
  const delivery=await db.emailDelivery.findFirstOrThrow({where:{vendorId:vendor.id,trigger:"student_portal_magic_link"}});
  const payload=revealEmailDeliveryPayload(delivery.payloadEncryptedEnvelope,{vendorId:vendor.id,deliveryId:delivery.id});expect(payload.subject).toContain("Learner sign-in link");
  const mailbox=payload.body.split(/\s+/u).find(part=>part.startsWith(`${baseURL}/portal/`));if(!mailbox||new URL(mailbox).origin!==baseURL)throw new Error("Synthetic mailbox origin mismatch");
  await page.goto(mailbox);
  await expect(page.getByRole("heading",{name:"My courses",exact:true})).toBeVisible();
  await page.reload();
  await expect(page.getByRole("heading",{name:"My courses",exact:true})).toBeVisible();
  await page.getByRole("link",{name:"Start course →",exact:true}).click();
  await expect(page.getByRole("heading",{name:product.name,exact:true})).toBeVisible();
  const player=page.locator("section").filter({has:page.getByRole("heading",{name:product.name,exact:true})});
  await expect(player).toHaveCount(1);
  // The course and notification preference panel each have a live region.
  // Keep the exact completion assertion scoped to the actual course player.
  const notifications=page.getByRole("region",{name:"Purchase notifications",exact:true});
  await notifications.getByRole("button",{name:"Load notification settings",exact:true}).click();
  await expect(notifications.getByRole("status",{name:"Purchase notification status",exact:true})).toHaveText("Notification settings loaded.");
  await expect(page.getByText("Learning progress",{exact:true})).toBeVisible();
  await player.getByRole("button",{name:"Mark complete",exact:true}).click();
  await expect(player.getByRole("status")).toHaveText("Lesson complete. Keep it up!");
  await page.reload();
  await expect(player.getByRole("button",{name:"Marked complete",exact:true})).toBeVisible();
  await page.getByRole("link",{name:"Course discussion",exact:true}).click();
  const form=page.getByRole("form",{name:"Post your experience",exact:true});
  await form.getByLabel("Display name",{exact:true}).fill("保留原文學員");
  await form.getByLabel("Share your learning experience",{exact:true}).fill("不翻譯使用者內容");
  await form.getByRole("button",{name:"Post your experience",exact:true}).click();
  await expect(page.getByRole("status")).toHaveText("Saved.");
  await page.reload();
  await expect(page.getByText("不翻譯使用者內容",{exact:true})).toBeVisible();
  // Inspect only public cache keys; no session/cookie values are read or logged.
  await page.evaluate(async()=>{await navigator.serviceWorker.ready;});
  await expect.poll(()=>page.evaluate(()=>Boolean(navigator.serviceWorker.controller))).toBe(true);
  const allowed=["/portal/icon-192.png","/portal/icon-512.png","/portal/manifest.webmanifest","/portal/offline.html"];
  const cachePaths=await page.evaluate(async()=>{const cache=await caches.open("celebratedeal-portal-public-v1");return (await cache.keys()).map(request=>new URL(request.url).pathname).sort();});expect(cachePaths).toEqual(allowed);
  const manifest=await page.request.get("/portal/manifest.webmanifest");expect(await manifest.json()).toMatchObject({start_url:"/portal/start.html",scope:"/portal/",display:"standalone"});
  // Follow the installed entry, not just the manifest string or a course URL.
  const installedManifest=await manifest.json();
  await page.goto(installedManifest.start_url);
  expect(new URL(page.url()).pathname).toBe(installedManifest.start_url);
  expect(new URL(page.url()).pathname.startsWith(installedManifest.scope)).toBe(true);
  await expect.poll(()=>page.evaluate(()=>Boolean(navigator.serviceWorker.controller))).toBe(true);
  await page.context().setOffline(true);
  const offlineEntry=await page.reload();
  expect(offlineEntry?.status()).toBe(503);
  await expect(page.getByRole("heading",{name:"You are offline",exact:true})).toBeVisible();
  expect(await page.evaluate(async()=>{const cache=await caches.open("celebratedeal-portal-public-v1");return (await cache.keys()).map(request=>new URL(request.url).pathname).sort();})).toEqual(allowed);
  await page.context().setOffline(false);
  await page.goto(course);
  const postsBefore=await db.courseCommunityPost.count({where:{vendorId:vendor.id}});
  await page.context().setOffline(true);
  await page.goto(course);
  await expect(page.getByRole("heading",{name:"You are offline",exact:true})).toBeVisible();
  await expect(page.getByText(product.name,{exact:true})).toHaveCount(0);
  const failed=await page.evaluate(async endpoint=>{try{await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:"{}"});return false;}catch{return true;}},`${course}/community/data`);expect(failed).toBe(true);expect(await db.courseCommunityPost.count({where:{vendorId:vendor.id}})).toBe(postsBefore);
  await page.context().setOffline(false);
  await page.goto(`${portal}`);
  await expect(page.getByRole("heading",{name:"My courses",exact:true})).toBeVisible();
  await page.goto(`/portal/${foreign.slug}`);
  await expect.poll(()=>new URL(page.url()).pathname).toBe(`/portal/${foreign.slug}/login`);expect(new URL(page.url()).origin).toBe(baseURL);expect(new URL(page.url()).searchParams.get("error")).toBe("unauthorized");
  await expect(page.getByText(product.name,{exact:true})).toHaveCount(0);
  await page.goto(portal);
  await db.$transaction(tx=>reconcileCommerceOrderRefund(tx,{orderId,vendorId:vendor.id,providerName:"synthetic",eventIdentity:randomUUID(),amountCents:10000,occurredAt:new Date()}));
  await page.goto(course);
  await expect(page.getByRole("heading",{name:product.name,exact:true})).toHaveCount(0);
  await page.goto(portal);
  await page.getByRole("button",{name:"Sign out securely",exact:true}).click();
  await expect(page).toHaveURL(new RegExp(`${portal}/login$`));
 }finally{await page.context().setOffline(false);
  await db.$disconnect();}
 // Owned synthetic rows are removed only with the disposable database.
});
