import { renderToStaticMarkup } from "react-dom/server";
import type { ComponentProps } from "react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import type { InteractionRolesWorkbench as InteractionRolesWorkbenchComponent } from "@/components/interaction-roles-workbench";

const mocks = vi.hoisted(() => ({ notFound: vi.fn(() => { throw new Error("NOT_FOUND"); }), requireVendorManager: vi.fn(), roleFindMany: vi.fn(), roleFindFirst: vi.fn(), eventFindMany: vi.fn(), imageAssetFindFirst: vi.fn(), getCsrfToken: vi.fn(), workbenchProps: null as Record<string, unknown> | null }));
vi.mock("next/navigation", () => ({ notFound: mocks.notFound }));
vi.mock("@/lib/auth", () => ({ requireVendorManager: mocks.requireVendorManager }));
vi.mock("@/lib/csrf", () => ({ getCsrfToken: mocks.getCsrfToken }));
vi.mock("@/lib/db", () => ({ getDb: () => ({ interactionRole: { findMany: mocks.roleFindMany, findFirst: mocks.roleFindFirst }, interactionEvent: { findMany: mocks.eventFindMany }, imageAsset: { findFirst: mocks.imageAssetFindFirst } }) }));
vi.mock("@/components/interaction-roles-workbench", () => ({ InteractionRolesWorkbench: (props: ComponentProps<typeof InteractionRolesWorkbenchComponent>) => { mocks.workbenchProps = props as Record<string, unknown>; return <div data-testid="roles-workbench">{JSON.stringify(props)}</div>; } }));
vi.mock("@/components/ui", () => ({ PageHeader: ({ title, description }: { title: string; description: string }) => <header><h1>{title}</h1><p>{description}</p></header> }));

import EditInteractionRolePage from "./page";

beforeEach(() => { vi.clearAllMocks(); mocks.workbenchProps = null; mocks.requireVendorManager.mockResolvedValue({ id: "vendor-1" }); mocks.roleFindMany.mockResolvedValue([{ id: "role-1", name: "主持人" }]); mocks.roleFindFirst.mockResolvedValue({ id: "role-2", vendorId: "vendor-1", name: "AI 助手", type: "assistant" }); mocks.eventFindMany.mockResolvedValue([{ eventType: "chat_message", script: { id: "script-1", name: "直播腳本", status: "published", _count: { lives: 2 } } }]); mocks.imageAssetFindFirst.mockResolvedValue(null); mocks.getCsrfToken.mockResolvedValue("csrf-token"); });

describe("/interaction-roles/[id]/edit route", () => {
  it("scopes list, selected role, reverse script usage, and live counts to the vendor", async () => { const html = renderToStaticMarkup(await EditInteractionRolePage({ params: Promise.resolve({ id: "role-2" }) })); expect(mocks.roleFindMany).toHaveBeenCalledWith({ where: { vendorId: "vendor-1" }, orderBy: { createdAt: "desc" } }); expect(mocks.roleFindFirst).toHaveBeenCalledWith({ where: { id: "role-2", vendorId: "vendor-1" } }); expect(mocks.eventFindMany).toHaveBeenCalledWith({ where: { roleId: "role-2", script: { vendorId: "vendor-1" } }, orderBy: [{ scriptId: "asc" }, { triggerSec: "asc" }], select: { eventType: true, script: { select: { id: true, name: true, status: true, _count: { select: { lives: { where: { vendorId: "vendor-1" } } } } } } } }); expect(html).toContain("點選左側互動角色"); expect(html).toContain("role-2"); expect(html).toContain("script-1"); expect(html).toContain("csrf-token"); });
  it("finds a ready avatar asset with the selected role URL and passes it through the real workbench prop contract", async () => { mocks.roleFindFirst.mockResolvedValue({ id: "role-2", vendorId: "vendor-1", name: "AI 助手", type: "assistant", avatarUrl: "https://cdn.example/avatar.png" }); mocks.imageAssetFindFirst.mockResolvedValue({ id: "asset-1" }); renderToStaticMarkup(await EditInteractionRolePage({ params: Promise.resolve({ id: "role-2" }) })); expect(mocks.imageAssetFindFirst).toHaveBeenCalledWith({ where: { vendorId: "vendor-1", status: "ready", publicUrl: "https://cdn.example/avatar.png" }, select: { id: true } }); expect(mocks.workbenchProps).toMatchObject({ initialAvatarAssetId: "asset-1" }); });
  it("passes an empty asset id when the avatar asset is missing", async () => { mocks.roleFindFirst.mockResolvedValue({ id: "role-2", vendorId: "vendor-1", name: "AI 助手", type: "assistant", avatarUrl: "https://cdn.example/missing.png" }); mocks.imageAssetFindFirst.mockResolvedValue(null); renderToStaticMarkup(await EditInteractionRolePage({ params: Promise.resolve({ id: "role-2" }) })); expect(mocks.imageAssetFindFirst).toHaveBeenCalledWith({ where: { vendorId: "vendor-1", status: "ready", publicUrl: "https://cdn.example/missing.png" }, select: { id: true } }); expect(mocks.workbenchProps).toMatchObject({ initialAvatarAssetId: "" }); });
  it("passes an empty asset id and skips lookup when avatar URL is empty", async () => { renderToStaticMarkup(await EditInteractionRolePage({ params: Promise.resolve({ id: "role-2" }) })); expect(mocks.imageAssetFindFirst).not.toHaveBeenCalled(); expect(mocks.workbenchProps).toMatchObject({ initialAvatarAssetId: "" }); });
  it("fails closed when a selected role is missing", async () => { mocks.roleFindFirst.mockResolvedValue(null); await expect(EditInteractionRolePage({ params: Promise.resolve({ id: "missing" }) })).rejects.toThrow("NOT_FOUND"); expect(mocks.notFound).toHaveBeenCalledExactlyOnceWith(); });
});
