import Link from "next/link";
import { registerAction } from "@/app/actions/auth-security-actions";
import { CsrfField } from "@/components/csrf-field";
import { FormSubmitButton } from "@/components/form-submit-button";

const errors: Record<string, string> = { invalid: "請確認資料完整，密碼至少 12 個字元。", exists: "這個 Email 已註冊，請直接登入。", rate_limited: "註冊嘗試過多，請稍後再試。", temporarily_unavailable: "註冊保護服務暫時無法使用。" };
export default async function RegisterPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const { error } = await searchParams;
  return <main className="grid min-h-screen place-items-center bg-gradient-to-b from-blue-50 to-white px-4 py-8"><section className="w-full max-w-lg rounded-2xl border border-slate-200 bg-white p-6 shadow-xl sm:p-8"><p className="text-sm font-bold text-blue-700">CelebrateDeal</p><h1 className="mt-2 text-3xl font-bold text-slate-950">建立你的商家 Workspace</h1><p className="mt-2 text-sm leading-6 text-slate-600">完成註冊後，我們會用 60 秒問卷替你準備第一個銷售專案。</p>{error ? <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{errors[error] ?? "註冊失敗，請稍後再試。"}</p> : null}<form action={registerAction} className="mt-6 grid gap-4"><CsrfField /><label className="grid gap-1.5 text-sm font-semibold text-slate-700">你的姓名<input name="name" required minLength={2} maxLength={80} autoComplete="name" className="h-11 rounded-lg border border-slate-200 px-3" /></label><label className="grid gap-1.5 text-sm font-semibold text-slate-700">商家名稱<input name="workspaceName" required minLength={2} maxLength={120} autoComplete="organization" className="h-11 rounded-lg border border-slate-200 px-3" /></label><label className="grid gap-1.5 text-sm font-semibold text-slate-700">Email<input name="email" type="email" required autoComplete="email" className="h-11 rounded-lg border border-slate-200 px-3" /></label><label className="grid gap-1.5 text-sm font-semibold text-slate-700">密碼<input name="password" type="password" required minLength={12} autoComplete="new-password" className="h-11 rounded-lg border border-slate-200 px-3" /><span className="font-normal text-slate-500">至少 12 個字元</span></label><FormSubmitButton pendingChildren="建立中…" pendingMessage="正在安全建立帳號與工作空間，請勿重複送出。" className="min-h-11 rounded-xl bg-blue-600 px-5 font-semibold text-white hover:bg-blue-700">建立帳號並開始設定</FormSubmitButton></form><p className="mt-5 text-center text-sm text-slate-600">已經有帳號？ <Link href="/login" className="font-semibold text-blue-700 hover:underline">返回登入</Link></p></section></main>;
}
